# Generated by Django 3.0.4 on 2020-03-28 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ban',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
