# Generated by Django 3.0.4 on 2020-03-28 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200328_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 6, 6, 13, 220775)),
        ),
    ]
