# Generated by Django 3.0.4 on 2020-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200328_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
