# Generated by Django 3.0.4 on 2020-03-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200328_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='permanent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
