# Generated by Django 3.0.4 on 2020-03-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20200325_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('content_quality', models.IntegerField(validators=[review.models.validate_rating])),
                ('anonymous', models.BooleanField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Prof')),
            ],
        ),
    ]
