# Generated by Django 3.0.4 on 2020-03-25 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_prof_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_review',
            name='content_quality',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
