# Generated by Django 3.0.4 on 2020-03-25 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0005_auto_20200325_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('course_difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('anonymous', models.BooleanField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='prof_review',
            constraint=models.UniqueConstraint(fields=('prof', 'author'), name='unique_prof_review'),
        ),
        migrations.AddField(
            model_name='course_review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course_review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course'),
        ),
        migrations.AddConstraint(
            model_name='course_review',
            constraint=models.UniqueConstraint(fields=('course', 'author'), name='unique_course_review'),
        ),
    ]
