# Generated by Django 3.0.4 on 2020-03-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20200325_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_review',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prof_review',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
