# Generated by Django 3.0.4 on 2020-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20200325_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_review',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prof_review',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
