# Generated by Django 3.0.4 on 2020-03-27 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0010_auto_20200327_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='c_rev_like',
            unique_together={('post', 'value', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='p_rev_like',
            unique_together={('post', 'value', 'user')},
        ),
    ]
